[build.nixpacksPlan.phases.build]
cmds = ['find /app/public -type d -exec chmod -R 777 {} +']

[build]
builder = "NIXPACKS"
buildCommand = "npm run build"

[deploy]
cmds = [
  "php artisan storage:link"
]