[build.nixpacksPlan.start]
cmd = "php artisan storage:link && node /assets/scripts/prestart.mjs /assets/nginx.template.conf /nginx.conf && (php-fpm -y /assets/php-fpm.conf & nginx -c /nginx.conf)"

[build]
builder = "NIXPACKS"
buildCommand = "npm run build"


