[build.nixpacksPlan.phases.install]
cmds = ['mkdir -p /var/log/nginx && mkdir -p /var/cache/nginx', 'composer install --ignore-platform-reqs', 'php artisan storage:link', 'npm ci']

[build]
builder = "NIXPACKS"
buildCommand = "npm run build"
