[build.nixpacksPlan.phases.build]
cmds = ['find /app/public -type d -exec chmod -R 777 {} +']

[build.nixpacksPlan.phases.install]
cmds = ['composer install --ignore-platform-reqs', 'php artisan storage:link']

[build]
builder = "NIXPACKS"
buildCommand = "npm run build"
