<?php

namespace App\Enums;

enum Pekerjaan: string
{
    case BELUM_TIDAK_BEKERJA = 'Belum/Tidak Bekerja';
    case IBU_RUMAH_TANGGA = 'Ibu Rumah Tangga';
    case PELAJAR_MAHASISWA = 'Pelajar/Mahasiswa';
    case PENSIUNAN = 'Pensiunan';
    case PEGAWAI_NEGERI_SIPIL = 'Pegawai Negeri Sipil';
    case TNI_POLRI = 'TNI/POLRI';
    case PERDAGANGAN = 'Pedagang';
    case PETANI_PEKEBUN = 'Petani/Pekebun';
    case PETERNAK = 'Peternak';
    case NELAYAN_PERIKANAN = 'Nelayan/Perikanan';
    case KONSTRUKSI = 'Pegawai Konstruksi';
    case KARYAWAN_SWASTA = 'Karyawan Swasta';
    case KARYAWAN_BUMN = 'Karyawan BUMN';
    case KARYAWAN_BUMD = 'Karyawan BUMD';
    case KARYAWAN_HONORER = 'Karyawan Honorer';
    case BURUH_HARIAN_LEPAS = 'Buruh Harian Lepas';
    case BURUH_TANI_PERKEBUNAN = 'Buruh Tani/Perkebunan';
    case BURUH_NELAYAN_PERIKANAN = 'Buruh Nelayan/Perikanan';
    case BURUH_PETERNAKAN = 'Buruh Peternakan';
    case ASISTEN_RUMAH_TANGGA = 'Asisten Rumah Tangga';
    case TUKANG_LISTRIK = 'Tukang Listrik';
    case TUKANG_BATU = 'Tukang Batu';
    case TUKANG_KAYU = 'Tukang Kayu';
    case TUKANG_SOL_SEPATU = 'Tukang Sol Sepatu';
    case TUKANG_LAS_PANDAI_BESI = 'Tukang Las/Pandai Besi';
    case TUKANG_JAHIT = 'Tukang Jahit';
    case PENATA_RIAS = 'Penata Rias';
    case PENATA_BUSANA = 'Penata Busana';
    case MEKANIK = 'Mekanik';
    case SENIMAN = 'Seniman';
    case DOKTER = 'Dokter';
    case PERANCANG_BUSANA = 'Perancang Busana';
    case PENTERJEMAH = 'Penterjemah';
    case WARTAWAN = 'Wartawan';
    case PEMUKA_AGAMA = 'Pemuka Agama';
    case JURU_MASAK = 'Juru Masak';
    case ANGGOTA_DPR_RI = 'Anggota DPR-RI';
    case ANGGOTA_DPD = 'Anggota DPD';
    case ANGGOTA_BPK = 'Anggota BPK';
    case PRESIDEN = 'Presiden';
    case WAKIL_PRESIDEN = 'Wakil Presiden';
    case ANGGOTA_MAHKAMAH_KONSTITUSI = 'Anggota Mahkamah Konstitusi';
    case ANGGOTA_KABINET_KEMENTERIAN = 'Anggota Kabinet/Kementerian';
    case DUTA_BESAR = 'Duta Besar';
    case GUBERNUR = 'Gubernur';
    case WAKIL_GUBERNUR = 'Wakil Gubernur';
    case BUPATI = 'Bupati';
    case WAKIL_BUPATI = 'Wakil Bupati';
    case WALIKOTA = 'Walikota';
    case WAKIL_WALIKOTA = 'Wakil Walikota';
    case ANGGOTA_DPRD_PROVINSI = 'Anggota DPRD Provinsi';
    case ANGGOTA_DPRD_KABUPATEN_KOTA = 'Anggota DPRD Kabupaten/Kota';
    case DOSEN = 'Dosen';
    case GURU = 'Guru';
    case PILOT = 'Pilot';
    case PRAMUGARI = 'Pramugari';
    case PERAWAT = 'Perawat';
    case APOTEKER = 'Apoteker';
    case PSIKIATER_PSIKOLOG = 'Psikiater/Psikolog';
    case PENYIAR_TELEVISI = 'Penyiar Televisi';
    case PENYIAR_RADIO = 'Penyiar Radio';
    case PELAUT = 'Pelaut';
    case PENELITI = 'Peneliti';
    case SOPIR = 'Sopir';
    case PERANGKAT_DESA = 'Perangkat Desa';
    case KEPALA_DESA = 'Kepala Desa';
    case WIRASWASTA = 'Wiraswasta';
    case ANGGOTA_LEMBAGA_TINGGI = 'Anggota Lembaga Tinggi';
    case ARTIS = 'Artis';
    case ATLIT = 'Atlit';
    case MANAJER = 'Manajer';
    case TENAGA_TATA_USAHA = 'Tenaga Tata Usaha';
    case OPERATOR = 'Operator';
    case PEKERJA_PENGOLAHAN_KERAJINAN = 'Pekerja Pengolahan, Kerajinan';
    case TEKNISI = 'Teknisi';
    case ASISTEN_AHLI = 'Asisten Ahli';
    case LAINNYA = 'Lainnya';

    public function getDescription(): string
    {
        return match($this) {
            self::BELUM_TIDAK_BEKERJA => 'Belum/Tidak Bekerja',
            self::IBU_RUMAH_TANGGA => 'Ibu Rumah Tangga',
            self::PELAJAR_MAHASISWA => 'Pelajar/Mahasiswa',
            self::PENSIUNAN => 'Pensiunan',
            self::PEGAWAI_NEGERI_SIPIL => 'Pegawai Negeri Sipil',
            self::TNI_POLRI => 'TNI/POLRI',
            self::PERDAGANGAN => 'Pedagang',
            self::PETANI_PEKEBUN => 'Petani/Pekebun',
            self::PETERNAK => 'Peternak',
            self::NELAYAN_PERIKANAN => 'Nelayan/Perikanan',
            self::KONSTRUKSI => 'Pegawai Konstruksi',
            self::KARYAWAN_SWASTA => 'Karyawan Swasta',
            self::KARYAWAN_BUMN => 'Karyawan BUMN',
            self::KARYAWAN_BUMD => 'Karyawan BUMD',
            self::KARYAWAN_HONORER => 'Karyawan Honorer',
            self::BURUH_HARIAN_LEPAS => 'Buruh Harian Lepas',
            self::BURUH_TANI_PERKEBUNAN => 'Buruh Tani/Perkebunan',
            self::BURUH_NELAYAN_PERIKANAN => 'Buruh Nelayan/Perikanan',
            self::BURUH_PETERNAKAN => 'Buruh Peternakan',
            self::ASISTEN_RUMAH_TANGGA => 'Asisten Rumah Tangga',
            self::TUKANG_LISTRIK => 'Tukang Listrik',
            self::TUKANG_BATU => 'Tukang Batu',
            self::TUKANG_KAYU => 'Tukang Kayu',
            self::TUKANG_SOL_SEPATU => 'Tukang Sol Sepatu',
            self::TUKANG_LAS_PANDAI_BESI => 'Tukang Las/Pandai Besi',
            self::TUKANG_JAHIT => 'Tukang Jahit',
            self::PENATA_RIAS => 'Penata Rias',
            self::PENATA_BUSANA => 'Penata Busana',
            self::MEKANIK => 'Mekanik',
            self::SENIMAN => 'Seniman',
            self::DOKTER => 'Dokter',
            self::PERANCANG_BUSANA => 'Perancang Busana',
            self::PENTERJEMAH => 'Penterjemah',
            self::WARTAWAN => 'Wartawan',
            self::PEMUKA_AGAMA => 'Pemuka Agama',
            self::JURU_MASAK => 'Juru Masak',
            self::ANGGOTA_DPR_RI => 'Anggota DPR-RI',
            self::ANGGOTA_DPD => 'Anggota DPD',
            self::ANGGOTA_BPK => 'Anggota BPK',
            self::PRESIDEN => 'Presiden',
            self::WAKIL_PRESIDEN => 'Wakil Presiden',
            self::ANGGOTA_MAHKAMAH_KONSTITUSI => 'Anggota Mahkamah Konstitusi',
            self::ANGGOTA_KABINET_KEMENTERIAN => 'Anggota Kabinet/Kementerian',
            self::DUTA_BESAR => 'Duta Besar',
            self::GUBERNUR => 'Gubernur',
            self::WAKIL_GUBERNUR => 'Wakil Gubernur',
            self::BUPATI => 'Bupati',
            self::WAKIL_BUPATI => 'Wakil Bupati',
            self::WALIKOTA => 'Walikota',
            self::WAKIL_WALIKOTA => 'Wakil Walikota',
            self::ANGGOTA_DPRD_PROVINSI => 'Anggota DPRD Provinsi',
            self::ANGGOTA_DPRD_KABUPATEN_KOTA => 'Anggota DPRD Kabupaten/Kota',
            self::DOSEN => 'Dosen',
            self::GURU => 'Guru',
            self::PILOT => 'Pilot',
            self::PRAMUGARI => 'Pramugari',
            self::PERAWAT => 'Perawat',
            self::APOTEKER => 'Apoteker',
            self::PSIKIATER_PSIKOLOG => 'Psikiater/Psikolog',
            self::PENYIAR_TELEVISI => 'Penyiar Televisi',
            self::PENYIAR_RADIO => 'Penyiar Radio',
            self::PELAUT => 'Pelaut',
            self::PENELITI => 'Peneliti',
            self::SOPIR => 'Sopir',
            self::PERANGKAT_DESA => 'Perangkat Desa',
            self::KEPALA_DESA => 'Kepala Desa',
            self::WIRASWASTA => 'Wiraswasta',
            self::ANGGOTA_LEMBAGA_TINGGI => 'Anggota Lembaga Tinggi',
            self::ARTIS => 'Artis',
            self::ATLIT => 'Atlit',
            self::MANAJER => 'Manajer',
            self::TENAGA_TATA_USAHA => 'Tenaga Tata Usaha',
            self::OPERATOR => 'Operator',
            self::PEKERJA_PENGOLAHAN_KERAJINAN => 'Pekerja Pengolahan, Kerajinan',
            self::TEKNISI => 'Teknisi',
            self::ASISTEN_AHLI => 'Asisten Ahli',
            self::LAINNYA => 'Lainnya',
        };
    }
}